### ISSUE TITLE
How to encode the `id_` in the `results_export_crowd/ vaniland.json` file?

### ISSUE THREAD

**Issue by dlct-wzx** [GAP-LAB-CUHK-SZ/TO-Scene#10]
Hello, thanks for the dataset. I am working on a test for desktop scene pose estimation, aiming to determine the pose of each instance within the overall environment. To facilitate this, I am looking to extract the rotation and translation matrices from the `results_export_crowd/vanilla.json` file. May I kindly ask if there is a specific way the objects in the point cloud file correspond to those in the JSON file? For instance, are they matched sequentially, considering that the `id_` field in the JSON file appears to be encoded?
![image](https://github.com/user-attachments/assets/aa937236-3adf-49d7-a4d8-265abf97e0d5)
![image](https://github.com/user-attachments/assets/3f86f1ff-5870-4356-b4e2-4b6ccf141c80)

**Comment by bbbbubble** [comment]
> Hello, thanks for the dataset. I am working on a test for desktop scene pose estimation, aiming to determine the pose of each instance within the overall environment. To facilitate this, I am looking to extract the rotation and translation matrices from the `results_export_crowd/vanilla.json` file. May I kindly ask if there is a specific way the objects in the point cloud file correspond to those in the JSON file? For instance, are they matched sequentially, considering that the `id_` field in the JSON file appears to be encoded? ![image](https://private-user-images.githubusercontent.com/80754785/387211936-aa937236-3adf-49d7-a4d8-265abf97e0d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMDkyMzYsIm5iZiI6MTczNTAwODkzNiwicGF0aCI6Ii84MDc1NDc4NS8zODcyMTE5MzYtYWE5MzcyMzYtM2FkZi00OWQ3LWE0ZDgtMjY1YWJmOTdlMGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAyNTUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZjYxZWM4MjA1ZWFlZWE2ZmVjYmEwNmZmYzU2ZGEzYTYxNDY0ZWIxOTQ5ZjU5MGYzMmIwNjc1ODA0NDQ3YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a3KMCkV3lt2hf2fqQ-lMYdVnJhSlriy0wq5N_sG9syI) ![image](https://private-user-images.githubusercontent.com/80754785/387212031-3f86f1ff-5870-4356-b4e2-4b6ccf141c80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMDkyMzYsIm5iZiI6MTczNTAwODkzNiwicGF0aCI6Ii84MDc1NDc4NS8zODcyMTIwMzEtM2Y4NmYxZmYtNTg3MC00MzU2LWI0ZTItNGI2Y2NmMTQxYzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAyNTUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YzdjZmQ1ZTA5MzNlY2UwMmJiZmFkMWY4OGE2YzFiODg2MzU3ZDJjZDc4ZjQ5NWNlN2MwOWM4ZWQxMzQzNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bqz4WJ_bmT6L0uE3UNAUBBhyTr0zGOpeaSDOPP5N1QM)

Sorry for the late reply. The JSON file is the raw scene data exported by our web annotation tool, while the final point cloud data is derived from processing this raw data. Since this work was done a few years ago, I don’t remember the details clearly, but there might not be a strict correspondence between them, or they could correspond in sequence. 

However, for your goal, you should be able to calculate the pose of each instance using the corresponding .npz file, rather than using the rotation data in the JSON file, because they are relative to the original ModelNet/ShapeNet dataset and may not be what you want.

**Comment by dlct-wzx** [comment]
Thank you for your reply.
