### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by Rampantsen** [GAP-LAB-CUHK-SZ/TO-Scene#5]
Hello, I followed the step of 3d object detection, but when I am running python main.py --mode train --config ./configs/train_heatmap.yaml, I encountered follow problem:

Loading configuration
{'resume': False, 'method': 'heatmap', 'exp_name': 'TO-crowrd_heatmap_1124', 'device': {'use_gpu': True, 'gpu_ids': '3'}, 'data': {'dataset': 'TOS_desk', 'data_dir': './data/TO-crowd-wHM', 'use_color': False, 'use_height': True, 'use_aug': True, 'batch_size': 8, 'num_workers': 8, 'ap_iou_thresh': 0.25, 'npoints': 40000}, 'model': {'input_feature_dim': 1}, 'optimizer': {'type': 'Adam', 'lr': 0.0001, 'beta1': 0.9, 'beta2': 0.999, 'eps': None, 'weight_decay': None}, 'scheduler': {'type': 'MultiStepLR', 'milestone': [50, 80], 'gamma': 0.2}, 'other': {'nepoch': 100, 'model_save_interval': 1, 'model_save_dir': './checkpoints', 'dump_result': True, 'dump_interval': 1000, 'test_interval': 10, 'log_interval': 100}, 'log': {'path': './checkpoints/TO-crowrd_heatmap_1124'}, 'config': './configs/train_heatmap.yaml', 'mode': 'train'}
Data save path: ./checkpoints/TO-crowrd_heatmap_1124
Loading device settings.
CPU mode is on.
Loading dataset.
Traceback (most recent call last):
  File "/home/ray/workspace/HRI_Project/TO-Scene/obj_det/main.py", line 25, in <module>
    train.run(cfg)
  File "/home/ray/workspace/HRI_Project/TO-Scene/obj_det/train.py", line 15, in run
    train_loader = get_dataloader(cfg.config, mode='train')
  File "/home/ray/workspace/HRI_Project/TO-Scene/obj_det/utils/train_test_utils.py", line 297, in get_dataloader
    from dataset.TOS_desk_dataset import TOS_Desk_Dataloader
  File "/home/ray/workspace/HRI_Project/TO-Scene/obj_det/dataset/TOS_desk_dataset.py", line 7, in <module>
    DC=DOS_desk_config()
  File "/home/ray/workspace/HRI_Project/TO-Scene/obj_det/data/model_utils_DOS.py", line 32, in __init__
    self.mean_size_arr = np.load(os.path.join('./data/doscannet_means_desklevel-axisalign-5e6.npz'))['arr_0']
  File "/home/ray/anaconda3/envs/pytorch/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './data/doscannet_means_desklevel-axisalign-5e6.npz'

It seems that it can't find file doscannet_means_desklevel-axisalign-5e6.npz, however I don't know where the file is.
Could you please tell me how to deal with this? 
Thanks very much.

**Comment by bbbbubble** [comment]
Thank you for your interest!

The file name in the code is wrong. You can find the file in the "means" folder here: https://github.com/GAP-LAB-CUHK-SZ/TO-Scene#2-meta-data.
