### ISSUE TITLE
unable to find To-real test dataset in readme.md

### ISSUE THREAD

**Issue by lzzwdd** [GAP-LAB-CUHK-SZ/TO-Scene#6]
Can you tell me  where it is?

thank you !

**Comment by mutianxu** [comment]
Hi,

Sorry, currently we are full of our plans.

We may consider releasing it in the near future.

Thanks!

**Comment by mutianxu** [comment]
Hi @lzzwdd ,

Good news! We have released TO-Real dataset.

You can find it in README now!

> Can you tell me where it is?
> 
> thank you !

**Comment by lzzwdd** [comment]
Thank you very much,I have successfully downloaded it!
